config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :genres
  get 'pages/index'
  devise_for :members
  devise_for :users
  resources :users, only: %w[index edit update]

  use_doorkeeper

  # 首頁
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ApiRoot => ApiRoot::PREFIX
  # Api UI 文件
  mount GrapeSwaggerRails::Engine => '/swagger'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :genre
  belongs_to :user

  scope :active, -> { where("(courses.started_at IS NULL or courses.started_at <= :date) AND (courses.ended_at IS NULL or courses.ended_at >= :date)", date: Date.today) }

  def is_active
    (started_at.nil? || started_at <= Date.today) && (ended_at.nil? || ended_at >= Date.today)
  end

  enum currency: [:NTD, :USD]

  has_many :member_courses
  has_many :members, through: :member_courses

  validates :expiration_day, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 30 }

  scope :can_buy, -> (member) do
    return all unless member

    excluded_course_ids = member.member_courses.ransack(expiration_date_gt: Time.current).result.distinct.pluck(:course_id)
    active.where.not(id: excluded_course_ids)
  end

  def self.ransackable_scopes(_auth_object = nil)
    [:can_buy]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  # sql constraint of uniqueness (沒有用): https://stackoverflow.com/questions/14622143/adding-unique-true-for-add-column-and-add-index-in-active-record
  validates :title, uniqueness: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :member_courses
  has_many :courses, through: :member_courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.authenticate(email, password)
    member = find_for_authentication(email: email)
    member&.valid_password?(password) ? member : nil
  end
end

app/models/member_course.rb
class MemberCourse < ApplicationRecord
  belongs_to :member, inverse_of: :member_courses
  belongs_to :course, inverse_of: :member_courses

  enum pay_method: [:credit_card]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:super_admin, :admin, :ordinary]

  def can_edit?
    admin? || super_admin?
  end

  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :is_admin, only: %i[ show edit update destroy ]
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses.rb or /courses.rb.json
  def index
    @courses = Course.all
  end

  # GET /courses.rb/1 or /courses.rb/1.json
  def show
  end

  # GET /courses.rb/new
  def new
    @course = Course.new
  end

  # GET /courses.rb/1/edit
  def edit
  end

  # POST /courses.rb or /courses.rb.json
  def create
    @course = current_user.courses.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to edit_course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses.rb/1 or /courses.rb/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to edit_course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses.rb/1 or /courses.rb/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:topic, :description, :currency, :started_at, :ended_at, :genre_id, :url, :expiration_day)
    end

    def is_admin
      redirect_to :root unless current_user&.can_edit?
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :is_admin
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to edit_genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to edit_genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:title)
    end

    def is_admin
      redirect_to :root unless current_user&.can_edit?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_admin
  before_action :set_user, only: %i(edit update destroy)

  def index
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = '更新成功'
    else
      flash[:alert] = '更新失敗'
    end

    redirect_to users_path
  end

  private

  def is_admin
    redirect_to :root unless current_user&.super_admin?
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit( :email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.slim
= form_for @course, url: { action: action }, html: { class: "nifty_form" } do |f|
  .card
    .card-body
      .form-group.mb-3
        = f.label :topic, "テーマ:", class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :topic, class: "form-control"
      .form-group.mb-3
        = f.label :description, "描述:", class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :description, class: "form-control"
      .form-group.mb-3
        = f.label :url, "URL:", class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :url, class: "form-control"
      .form-group.mb-3
        = f.label :started_at, "開始時間:", class: "col-md-4 control-label"
        .col-md-8
          = f.datetime_select :started_at, ampm: true, minute_step: 15, class: "form-control"
      .form-group.mb-3
        = f.label :ended_at, "結束時間:", class: "col-md-4 control-label"
        .col-md-8
          = f.datetime_select :ended_at, ampm: true, minute_step: 15, class: "form-control"
      .form-group.mb-3
        = f.label :content, "類別:", class: "col-md-4 control-label"
        .col-md-8
          = f.select :genre_id, options_for_select(Genre.all.map { [_1.title, _1.id] }, @course&.genre_id), {}, class: "form-control"
      .form-group.mb-3
        = f.label :currency, "幣別:", class: "col-md-4 control-label"
        .col-md-8
          = f.select :currency, options_for_select(Course.currencies.map{|_| [_[0], _[0]]}, @course&.currency), {}, class: "form-control"
      .form-group
        = f.submit "送出", class: "btn btn-primary"
        = link_to "回首頁", root_path, class: "btn btn-warning"

app/views/courses/edit.html.erb
<h3>編輯</h3>
<%= render partial: 'form', locals: { action: 'update' } %>

app/views/courses/index.html.slim
- if @courses.length.positive?
  table#courses-table.table.data-table
    thead
      tr
        td 類別
        td 上架狀態
        td
    tbody
      - @courses.each do |course|
        tr
          td = course.topic
          td
            - if course.is_active
              = tag.div "ON檔", class: "btn btn-secondary btn-sm not-allowed"
            - else
              = tag.div "OFF檔", class: "btn btn-danger btn-sm not-allowed"
          td
            - if current_user&.can_edit?
              = link_to "編輯", edit_course_path(course), class: "btn btn-secondary btn-sm", disabled: true
              = link_to "刪除", course_path(course), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "確定要刪除這筆資料嗎?" }
- else
  p 目前尚有任何內容

- if current_user&.can_edit?
  = link_to "新增", new_course_path, class: "btn btn-primary"

css:
  .not-allowed {
      cursor: not-allowed;
  }

app/views/courses/new.html.erb
<h3>新增</h3>
<%= render partial: 'form', locals: { action: 'create' } %>

app/views/genres/_form.html.slim
= form_for @genre || :genre, url: { action: action }, html: { class: "nifty_form" } do |f|
  .card
    .card-body
      .form-group.mb-3
        = f.label :title, "類別:", class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :title, class: "form-control"
      .form-group
        = f.submit "送出", class: "btn btn-primary"
        = link_to "回首頁", genres_path, class: "btn btn-warning"

app/views/genres/index.html.slim
- if @genres.length.positive?
  table#genres-table.table.data-table
    thead
      tr
        td 類別
        td
    tbody
      - @genres.each do |genre|
        tr
          td= genre.title
          td
            - if current_user&.can_edit?
              = link_to "編輯", edit_genre_path(genre), class: "btn btn-secondary btn-sm", disabled: true
              = link_to "刪除", genre_path(genre), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "確定要刪除這筆資料嗎?" }
- else
  p 目前尚有任何內容

- if current_user&.can_edit?
  = link_to "新增", new_genre_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snapaskapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Snapask App", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <% if current_user.super_admin? %>
              <li class="nav-item">
                <%= link_to "使用者", users_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "類別", genres_path, class: "nav-link" %>
              </li>
            <% end %>
          <% end %>
          <li class="nav-item">
            <%= link_to "課程", courses_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               href="#"
               id="navbarDropdown"
               role="button"
               data-bs-toggle="dropdown"
               aria-expanded="false">
              <%= user_signed_in? ? "HI! #{current_user.email.split("@").first}" : "Guest" %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "login", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li class="nav-item">
                  <%= link_to "register", new_user_registration_path, class: "dropdown-item" %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <form class="d-flex mx-lg-2">
          <input class="form-control me-2" type="text" placeholder="Search">
          <button class="btn btn-primary" type="button">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.slim
h1 簡易購客App

app/views/users/edit.html.erb
<h3>編輯</h3>

<%= form_for @user, url: { action: 'update' }, html: { class: "nifty_form" } do |f| %>
	<div class="card">
		<div class="card-body">
			<div class="form-group mb-3">
			</div>
			
			<div class="form-group mb-3">
				<%= f.label :email, "email:", class: "col-md-4 control-label" %>
				<div class="col-md-8">
					<%= f.text_field :email, class: "form-control" %>
				</div>
			</div>
			
			<div class="form-group mb-3">
				<%= f.label :role, "角色權限:", class: "col-md-4 control-label" %>
				<div class="col-md-8">
					<%= f.select :role, options_for_select(User.roles.map(&:itself), @user.role), {}, class: "form-control" %>
				</div>
			</div>
			
			<div class="form-group">
				<%= f.submit "送出", class: "btn btn-primary" %>
				<%= link_to "回首頁", root_path, class: "btn btn-warning" %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/index.html.erb
<div data-controller="articles">
	<!--	<table class="table data-table" id="articles-table">-->
	<table class="table data-table">
		<thead>
		<tr>
			<td>Email</td>
			<td>角色權限</td>
			<td></td>
		</tr>
		</thead>
		<tbody>
		<% User.all.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td><%= user.role %></td>
				<td>
					<%= link_to "編輯", edit_user_path(user), class: "btn btn-secondary btn-sm" %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>